# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UFT_Ui.ui'
#
# Created: Wed Oct 18 09:57:19 2017
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(1222, 670)
        Form.setMinimumSize(QtCore.QSize(0, 0))
        self.tabWidget = QtGui.QTabWidget(Form)
        self.tabWidget.setGeometry(QtCore.QRect(490, 70, 721, 541))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab_cable = QtGui.QWidget()
        self.tab_cable.setObjectName(_fromUtf8("tab_cable"))
        self.CablelineEdit_16 = QtGui.QLineEdit(self.tab_cable)
        self.CablelineEdit_16.setGeometry(QtCore.QRect(460, 420, 209, 20))
        self.CablelineEdit_16.setObjectName(_fromUtf8("CablelineEdit_16"))
        self.CablelineEdit_10 = QtGui.QLineEdit(self.tab_cable)
        self.CablelineEdit_10.setGeometry(QtCore.QRect(460, 120, 209, 20))
        self.CablelineEdit_10.setObjectName(_fromUtf8("CablelineEdit_10"))
        self.CablelineEdit_5 = QtGui.QLineEdit(self.tab_cable)
        self.CablelineEdit_5.setGeometry(QtCore.QRect(130, 270, 209, 20))
        self.CablelineEdit_5.setObjectName(_fromUtf8("CablelineEdit_5"))
        self.CablelineEdit_9 = QtGui.QLineEdit(self.tab_cable)
        self.CablelineEdit_9.setGeometry(QtCore.QRect(460, 70, 209, 20))
        self.CablelineEdit_9.setObjectName(_fromUtf8("CablelineEdit_9"))
        self.CablelineEdit_11 = QtGui.QLineEdit(self.tab_cable)
        self.CablelineEdit_11.setGeometry(QtCore.QRect(460, 170, 209, 20))
        self.CablelineEdit_11.setObjectName(_fromUtf8("CablelineEdit_11"))
        self.CablelineEdit_14 = QtGui.QLineEdit(self.tab_cable)
        self.CablelineEdit_14.setGeometry(QtCore.QRect(460, 320, 209, 20))
        self.CablelineEdit_14.setObjectName(_fromUtf8("CablelineEdit_14"))
        self.CablelineEdit_6 = QtGui.QLineEdit(self.tab_cable)
        self.CablelineEdit_6.setGeometry(QtCore.QRect(130, 320, 209, 20))
        self.CablelineEdit_6.setObjectName(_fromUtf8("CablelineEdit_6"))
        self.CablelineEdit_15 = QtGui.QLineEdit(self.tab_cable)
        self.CablelineEdit_15.setGeometry(QtCore.QRect(460, 370, 209, 20))
        self.CablelineEdit_15.setObjectName(_fromUtf8("CablelineEdit_15"))
        self.CablelineEdit_1 = QtGui.QLineEdit(self.tab_cable)
        self.CablelineEdit_1.setGeometry(QtCore.QRect(130, 70, 209, 20))
        self.CablelineEdit_1.setObjectName(_fromUtf8("CablelineEdit_1"))
        self.CablelineEdit_12 = QtGui.QLineEdit(self.tab_cable)
        self.CablelineEdit_12.setGeometry(QtCore.QRect(460, 220, 209, 20))
        self.CablelineEdit_12.setObjectName(_fromUtf8("CablelineEdit_12"))
        self.CablelineEdit_4 = QtGui.QLineEdit(self.tab_cable)
        self.CablelineEdit_4.setGeometry(QtCore.QRect(130, 220, 209, 20))
        self.CablelineEdit_4.setObjectName(_fromUtf8("CablelineEdit_4"))
        self.CablelineEdit_7 = QtGui.QLineEdit(self.tab_cable)
        self.CablelineEdit_7.setGeometry(QtCore.QRect(130, 370, 209, 20))
        self.CablelineEdit_7.setObjectName(_fromUtf8("CablelineEdit_7"))
        self.CablelineEdit_13 = QtGui.QLineEdit(self.tab_cable)
        self.CablelineEdit_13.setGeometry(QtCore.QRect(460, 270, 209, 20))
        self.CablelineEdit_13.setObjectName(_fromUtf8("CablelineEdit_13"))
        self.CablelineEdit_2 = QtGui.QLineEdit(self.tab_cable)
        self.CablelineEdit_2.setGeometry(QtCore.QRect(130, 120, 209, 20))
        self.CablelineEdit_2.setObjectName(_fromUtf8("CablelineEdit_2"))
        self.CablelineEdit_8 = QtGui.QLineEdit(self.tab_cable)
        self.CablelineEdit_8.setGeometry(QtCore.QRect(130, 420, 209, 20))
        self.CablelineEdit_8.setObjectName(_fromUtf8("CablelineEdit_8"))
        self.CablelineEdit_3 = QtGui.QLineEdit(self.tab_cable)
        self.CablelineEdit_3.setGeometry(QtCore.QRect(130, 170, 209, 20))
        self.CablelineEdit_3.setObjectName(_fromUtf8("CablelineEdit_3"))
        self.label = QtGui.QLabel(self.tab_cable)
        self.label.setGeometry(QtCore.QRect(70, 70, 46, 13))
        self.label.setObjectName(_fromUtf8("label"))
        self.label_17 = QtGui.QLabel(self.tab_cable)
        self.label_17.setGeometry(QtCore.QRect(70, 120, 46, 13))
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.label_18 = QtGui.QLabel(self.tab_cable)
        self.label_18.setGeometry(QtCore.QRect(70, 170, 46, 13))
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.label_19 = QtGui.QLabel(self.tab_cable)
        self.label_19.setGeometry(QtCore.QRect(70, 220, 46, 13))
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.label_20 = QtGui.QLabel(self.tab_cable)
        self.label_20.setGeometry(QtCore.QRect(70, 270, 46, 13))
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.label_21 = QtGui.QLabel(self.tab_cable)
        self.label_21.setGeometry(QtCore.QRect(70, 320, 46, 13))
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.label_22 = QtGui.QLabel(self.tab_cable)
        self.label_22.setGeometry(QtCore.QRect(70, 370, 46, 13))
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.label_23 = QtGui.QLabel(self.tab_cable)
        self.label_23.setGeometry(QtCore.QRect(70, 420, 46, 13))
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.label_24 = QtGui.QLabel(self.tab_cable)
        self.label_24.setGeometry(QtCore.QRect(400, 70, 46, 13))
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.label_25 = QtGui.QLabel(self.tab_cable)
        self.label_25.setGeometry(QtCore.QRect(400, 120, 46, 13))
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.label_26 = QtGui.QLabel(self.tab_cable)
        self.label_26.setGeometry(QtCore.QRect(400, 170, 46, 13))
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.label_27 = QtGui.QLabel(self.tab_cable)
        self.label_27.setGeometry(QtCore.QRect(400, 220, 46, 13))
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.label_28 = QtGui.QLabel(self.tab_cable)
        self.label_28.setGeometry(QtCore.QRect(400, 270, 46, 13))
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.label_29 = QtGui.QLabel(self.tab_cable)
        self.label_29.setGeometry(QtCore.QRect(400, 320, 46, 13))
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.label_30 = QtGui.QLabel(self.tab_cable)
        self.label_30.setGeometry(QtCore.QRect(400, 370, 46, 13))
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.label_31 = QtGui.QLabel(self.tab_cable)
        self.label_31.setGeometry(QtCore.QRect(400, 420, 46, 13))
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.tabWidget.addTab(self.tab_cable, _fromUtf8(""))
        self.tab_hybridcell = QtGui.QWidget()
        self.tab_hybridcell.setObjectName(_fromUtf8("tab_hybridcell"))
        self.BatterylineEdit_10 = QtGui.QLineEdit(self.tab_hybridcell)
        self.BatterylineEdit_10.setGeometry(QtCore.QRect(460, 120, 209, 20))
        self.BatterylineEdit_10.setObjectName(_fromUtf8("BatterylineEdit_10"))
        self.BatterylineEdit_5 = QtGui.QLineEdit(self.tab_hybridcell)
        self.BatterylineEdit_5.setGeometry(QtCore.QRect(130, 270, 209, 20))
        self.BatterylineEdit_5.setObjectName(_fromUtf8("BatterylineEdit_5"))
        self.BatterylineEdit_9 = QtGui.QLineEdit(self.tab_hybridcell)
        self.BatterylineEdit_9.setGeometry(QtCore.QRect(460, 70, 209, 20))
        self.BatterylineEdit_9.setObjectName(_fromUtf8("BatterylineEdit_9"))
        self.BatterylineEdit_11 = QtGui.QLineEdit(self.tab_hybridcell)
        self.BatterylineEdit_11.setGeometry(QtCore.QRect(460, 170, 209, 20))
        self.BatterylineEdit_11.setObjectName(_fromUtf8("BatterylineEdit_11"))
        self.BatterylineEdit_14 = QtGui.QLineEdit(self.tab_hybridcell)
        self.BatterylineEdit_14.setGeometry(QtCore.QRect(460, 320, 209, 20))
        self.BatterylineEdit_14.setObjectName(_fromUtf8("BatterylineEdit_14"))
        self.BatterylineEdit_6 = QtGui.QLineEdit(self.tab_hybridcell)
        self.BatterylineEdit_6.setGeometry(QtCore.QRect(130, 320, 209, 20))
        self.BatterylineEdit_6.setObjectName(_fromUtf8("BatterylineEdit_6"))
        self.BatterylineEdit_15 = QtGui.QLineEdit(self.tab_hybridcell)
        self.BatterylineEdit_15.setGeometry(QtCore.QRect(460, 370, 209, 20))
        self.BatterylineEdit_15.setObjectName(_fromUtf8("BatterylineEdit_15"))
        self.BatterylineEdit_1 = QtGui.QLineEdit(self.tab_hybridcell)
        self.BatterylineEdit_1.setGeometry(QtCore.QRect(130, 70, 209, 20))
        self.BatterylineEdit_1.setObjectName(_fromUtf8("BatterylineEdit_1"))
        self.BatterylineEdit_12 = QtGui.QLineEdit(self.tab_hybridcell)
        self.BatterylineEdit_12.setGeometry(QtCore.QRect(460, 220, 209, 20))
        self.BatterylineEdit_12.setObjectName(_fromUtf8("BatterylineEdit_12"))
        self.BatterylineEdit_4 = QtGui.QLineEdit(self.tab_hybridcell)
        self.BatterylineEdit_4.setGeometry(QtCore.QRect(130, 220, 209, 20))
        self.BatterylineEdit_4.setObjectName(_fromUtf8("BatterylineEdit_4"))
        self.BatterylineEdit_7 = QtGui.QLineEdit(self.tab_hybridcell)
        self.BatterylineEdit_7.setGeometry(QtCore.QRect(130, 370, 209, 20))
        self.BatterylineEdit_7.setObjectName(_fromUtf8("BatterylineEdit_7"))
        self.BatterylineEdit_13 = QtGui.QLineEdit(self.tab_hybridcell)
        self.BatterylineEdit_13.setGeometry(QtCore.QRect(460, 270, 209, 20))
        self.BatterylineEdit_13.setObjectName(_fromUtf8("BatterylineEdit_13"))
        self.BatterylineEdit_16 = QtGui.QLineEdit(self.tab_hybridcell)
        self.BatterylineEdit_16.setGeometry(QtCore.QRect(460, 420, 209, 20))
        self.BatterylineEdit_16.setObjectName(_fromUtf8("BatterylineEdit_16"))
        self.BatterylineEdit_2 = QtGui.QLineEdit(self.tab_hybridcell)
        self.BatterylineEdit_2.setGeometry(QtCore.QRect(130, 120, 209, 20))
        self.BatterylineEdit_2.setObjectName(_fromUtf8("BatterylineEdit_2"))
        self.BatterylineEdit_8 = QtGui.QLineEdit(self.tab_hybridcell)
        self.BatterylineEdit_8.setGeometry(QtCore.QRect(130, 420, 209, 20))
        self.BatterylineEdit_8.setObjectName(_fromUtf8("BatterylineEdit_8"))
        self.BatterylineEdit_3 = QtGui.QLineEdit(self.tab_hybridcell)
        self.BatterylineEdit_3.setGeometry(QtCore.QRect(130, 170, 209, 20))
        self.BatterylineEdit_3.setObjectName(_fromUtf8("BatterylineEdit_3"))
        self.label_32 = QtGui.QLabel(self.tab_hybridcell)
        self.label_32.setGeometry(QtCore.QRect(400, 270, 46, 13))
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.label_33 = QtGui.QLabel(self.tab_hybridcell)
        self.label_33.setGeometry(QtCore.QRect(70, 170, 46, 13))
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self.label_34 = QtGui.QLabel(self.tab_hybridcell)
        self.label_34.setGeometry(QtCore.QRect(400, 70, 46, 13))
        self.label_34.setObjectName(_fromUtf8("label_34"))
        self.label_35 = QtGui.QLabel(self.tab_hybridcell)
        self.label_35.setGeometry(QtCore.QRect(400, 170, 46, 13))
        self.label_35.setObjectName(_fromUtf8("label_35"))
        self.label_36 = QtGui.QLabel(self.tab_hybridcell)
        self.label_36.setGeometry(QtCore.QRect(400, 370, 46, 13))
        self.label_36.setObjectName(_fromUtf8("label_36"))
        self.label_37 = QtGui.QLabel(self.tab_hybridcell)
        self.label_37.setGeometry(QtCore.QRect(70, 370, 46, 13))
        self.label_37.setObjectName(_fromUtf8("label_37"))
        self.label_38 = QtGui.QLabel(self.tab_hybridcell)
        self.label_38.setGeometry(QtCore.QRect(400, 120, 46, 13))
        self.label_38.setObjectName(_fromUtf8("label_38"))
        self.label_39 = QtGui.QLabel(self.tab_hybridcell)
        self.label_39.setGeometry(QtCore.QRect(70, 320, 46, 13))
        self.label_39.setObjectName(_fromUtf8("label_39"))
        self.label_40 = QtGui.QLabel(self.tab_hybridcell)
        self.label_40.setGeometry(QtCore.QRect(70, 70, 46, 13))
        self.label_40.setObjectName(_fromUtf8("label_40"))
        self.label_41 = QtGui.QLabel(self.tab_hybridcell)
        self.label_41.setGeometry(QtCore.QRect(70, 220, 46, 13))
        self.label_41.setObjectName(_fromUtf8("label_41"))
        self.label_42 = QtGui.QLabel(self.tab_hybridcell)
        self.label_42.setGeometry(QtCore.QRect(70, 120, 46, 13))
        self.label_42.setObjectName(_fromUtf8("label_42"))
        self.label_43 = QtGui.QLabel(self.tab_hybridcell)
        self.label_43.setGeometry(QtCore.QRect(70, 270, 46, 13))
        self.label_43.setObjectName(_fromUtf8("label_43"))
        self.label_44 = QtGui.QLabel(self.tab_hybridcell)
        self.label_44.setGeometry(QtCore.QRect(70, 420, 46, 13))
        self.label_44.setObjectName(_fromUtf8("label_44"))
        self.label_45 = QtGui.QLabel(self.tab_hybridcell)
        self.label_45.setGeometry(QtCore.QRect(400, 220, 46, 13))
        self.label_45.setObjectName(_fromUtf8("label_45"))
        self.label_46 = QtGui.QLabel(self.tab_hybridcell)
        self.label_46.setGeometry(QtCore.QRect(400, 320, 46, 13))
        self.label_46.setObjectName(_fromUtf8("label_46"))
        self.label_47 = QtGui.QLabel(self.tab_hybridcell)
        self.label_47.setGeometry(QtCore.QRect(400, 420, 46, 13))
        self.label_47.setObjectName(_fromUtf8("label_47"))
        self.tabWidget.addTab(self.tab_hybridcell, _fromUtf8(""))
        self.info = QtGui.QWidget()
        self.info.setObjectName(_fromUtf8("info"))
        self.groupBox_5 = QtGui.QGroupBox(self.info)
        self.groupBox_5.setGeometry(QtCore.QRect(368, 10, 341, 501))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_5.sizePolicy().hasHeightForWidth())
        self.groupBox_5.setSizePolicy(sizePolicy)
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.layoutWidget = QtGui.QWidget(self.groupBox_5)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 23, 321, 311))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.gridLayout_7 = QtGui.QGridLayout(self.layoutWidget)
        self.gridLayout_7.setMargin(0)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.imageLabel2 = QtGui.QLabel(self.layoutWidget)
        self.imageLabel2.setMaximumSize(QtCore.QSize(232, 235))
        self.imageLabel2.setText(_fromUtf8(""))
        self.imageLabel2.setObjectName(_fromUtf8("imageLabel2"))
        self.gridLayout_7.addWidget(self.imageLabel2, 0, 1, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.imageLabel3 = QtGui.QLabel(self.layoutWidget)
        self.imageLabel3.setMaximumSize(QtCore.QSize(233, 234))
        self.imageLabel3.setText(_fromUtf8(""))
        self.imageLabel3.setObjectName(_fromUtf8("imageLabel3"))
        self.gridLayout_7.addWidget(self.imageLabel3, 1, 0, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.imageLabel4 = QtGui.QLabel(self.layoutWidget)
        self.imageLabel4.setMaximumSize(QtCore.QSize(232, 234))
        self.imageLabel4.setText(_fromUtf8(""))
        self.imageLabel4.setObjectName(_fromUtf8("imageLabel4"))
        self.gridLayout_7.addWidget(self.imageLabel4, 1, 1, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.imageLabel1 = QtGui.QLabel(self.layoutWidget)
        self.imageLabel1.setMaximumSize(QtCore.QSize(233, 235))
        self.imageLabel1.setText(_fromUtf8(""))
        self.imageLabel1.setObjectName(_fromUtf8("imageLabel1"))
        self.gridLayout_7.addWidget(self.imageLabel1, 0, 0, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.groupBox_6 = QtGui.QGroupBox(self.info)
        self.groupBox_6.setGeometry(QtCore.QRect(10, 10, 351, 501))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_6.sizePolicy().hasHeightForWidth())
        self.groupBox_6.setSizePolicy(sizePolicy)
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.info_textBrowser = QtGui.QTextBrowser(self.groupBox_6)
        self.info_textBrowser.setGeometry(QtCore.QRect(10, 20, 331, 471))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.info_textBrowser.sizePolicy().hasHeightForWidth())
        self.info_textBrowser.setSizePolicy(sizePolicy)
        self.info_textBrowser.setAutoFillBackground(True)
        self.info_textBrowser.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.info_textBrowser.setObjectName(_fromUtf8("info_textBrowser"))
        self.tabWidget.addTab(self.info, _fromUtf8(""))
        self.charts = QtGui.QWidget()
        self.charts.setObjectName(_fromUtf8("charts"))
        self.gridLayout_3 = QtGui.QGridLayout(self.charts)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.radioButton = QtGui.QRadioButton(self.charts)
        self.radioButton.setObjectName(_fromUtf8("radioButton"))
        self.buttonGroup = QtGui.QButtonGroup(Form)
        self.buttonGroup.setObjectName(_fromUtf8("buttonGroup"))
        self.buttonGroup.addButton(self.radioButton)
        self.horizontalLayout_3.addWidget(self.radioButton)
        self.radioButton_2 = QtGui.QRadioButton(self.charts)
        self.radioButton_2.setObjectName(_fromUtf8("radioButton_2"))
        self.buttonGroup.addButton(self.radioButton_2)
        self.horizontalLayout_3.addWidget(self.radioButton_2)
        self.radioButton_3 = QtGui.QRadioButton(self.charts)
        self.radioButton_3.setObjectName(_fromUtf8("radioButton_3"))
        self.buttonGroup.addButton(self.radioButton_3)
        self.horizontalLayout_3.addWidget(self.radioButton_3)
        self.gridLayout_3.addLayout(self.horizontalLayout_3, 0, 0, 1, 1)
        self.groupBox_7 = QtGui.QGroupBox(self.charts)
        self.groupBox_7.setObjectName(_fromUtf8("groupBox_7"))
        self.gridLayout_10 = QtGui.QGridLayout(self.groupBox_7)
        self.gridLayout_10.setObjectName(_fromUtf8("gridLayout_10"))
        self.mplwidget = MatplotlibWidget(self.groupBox_7)
        self.mplwidget.setObjectName(_fromUtf8("mplwidget"))
        self.gridLayout_10.addWidget(self.mplwidget, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox_7, 1, 0, 1, 1)
        self.groupBox_8 = QtGui.QGroupBox(self.charts)
        self.groupBox_8.setObjectName(_fromUtf8("groupBox_8"))
        self.gridLayout_11 = QtGui.QGridLayout(self.groupBox_8)
        self.gridLayout_11.setObjectName(_fromUtf8("gridLayout_11"))
        self.mplwidget_2 = MatplotlibWidget(self.groupBox_8)
        self.mplwidget_2.setObjectName(_fromUtf8("mplwidget_2"))
        self.gridLayout_11.addWidget(self.mplwidget_2, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox_8, 1, 1, 1, 1)
        self.groupBox_9 = QtGui.QGroupBox(self.charts)
        self.groupBox_9.setObjectName(_fromUtf8("groupBox_9"))
        self.gridLayout_12 = QtGui.QGridLayout(self.groupBox_9)
        self.gridLayout_12.setObjectName(_fromUtf8("gridLayout_12"))
        self.mplwidget_3 = MatplotlibWidget(self.groupBox_9)
        self.mplwidget_3.setObjectName(_fromUtf8("mplwidget_3"))
        self.gridLayout_12.addWidget(self.mplwidget_3, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox_9, 2, 0, 1, 1)
        self.groupBox_10 = QtGui.QGroupBox(self.charts)
        self.groupBox_10.setObjectName(_fromUtf8("groupBox_10"))
        self.gridLayout_13 = QtGui.QGridLayout(self.groupBox_10)
        self.gridLayout_13.setObjectName(_fromUtf8("gridLayout_13"))
        self.mplwidget_4 = MatplotlibWidget(self.groupBox_10)
        self.mplwidget_4.setObjectName(_fromUtf8("mplwidget_4"))
        self.gridLayout_13.addWidget(self.mplwidget_4, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox_10, 2, 1, 1, 1)
        self.tabWidget.addTab(self.charts, _fromUtf8(""))
        self.configuration = QtGui.QWidget()
        self.configuration.setObjectName(_fromUtf8("configuration"))
        self.gridLayout_9 = QtGui.QGridLayout(self.configuration)
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.partNum_comboBox = QtGui.QComboBox(self.configuration)
        self.partNum_comboBox.setObjectName(_fromUtf8("partNum_comboBox"))
        self.gridLayout_4.addWidget(self.partNum_comboBox, 1, 0, 1, 1)
        self.label_PN = QtGui.QLabel(self.configuration)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Unicode MS"))
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_PN.setFont(font)
        self.label_PN.setObjectName(_fromUtf8("label_PN"))
        self.gridLayout_4.addWidget(self.label_PN, 0, 0, 1, 1)
        self.label_REV = QtGui.QLabel(self.configuration)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setBold(True)
        font.setWeight(75)
        self.label_REV.setFont(font)
        self.label_REV.setObjectName(_fromUtf8("label_REV"))
        self.gridLayout_4.addWidget(self.label_REV, 0, 1, 1, 1)
        self.revision_comboBox = QtGui.QComboBox(self.configuration)
        self.revision_comboBox.setObjectName(_fromUtf8("revision_comboBox"))
        self.gridLayout_4.addWidget(self.revision_comboBox, 1, 1, 1, 1)
        self.label_DES = QtGui.QLabel(self.configuration)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Unicode MS"))
        font.setBold(True)
        font.setWeight(75)
        self.label_DES.setFont(font)
        self.label_DES.setObjectName(_fromUtf8("label_DES"))
        self.gridLayout_4.addWidget(self.label_DES, 0, 2, 1, 1)
        self.descriptionLabel = QtGui.QLabel(self.configuration)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.descriptionLabel.setFont(font)
        self.descriptionLabel.setText(_fromUtf8(""))
        self.descriptionLabel.setObjectName(_fromUtf8("descriptionLabel"))
        self.gridLayout_4.addWidget(self.descriptionLabel, 1, 2, 1, 1)
        self.gridLayout_9.addLayout(self.gridLayout_4, 0, 0, 1, 1)
        self.test_item_tableView = QtGui.QTableView(self.configuration)
        self.test_item_tableView.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.test_item_tableView.setObjectName(_fromUtf8("test_item_tableView"))
        self.gridLayout_9.addWidget(self.test_item_tableView, 1, 0, 1, 1)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.submit_pushButton = QtGui.QPushButton(self.configuration)
        self.submit_pushButton.setEnabled(False)
        self.submit_pushButton.setObjectName(_fromUtf8("submit_pushButton"))
        self.horizontalLayout_5.addWidget(self.submit_pushButton)
        self.checkBox = QtGui.QCheckBox(self.configuration)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox.sizePolicy().hasHeightForWidth())
        self.checkBox.setSizePolicy(sizePolicy)
        self.checkBox.setObjectName(_fromUtf8("checkBox"))
        self.horizontalLayout_5.addWidget(self.checkBox)
        self.gridLayout_9.addLayout(self.horizontalLayout_5, 2, 0, 1, 1)
        self.tabWidget.addTab(self.configuration, _fromUtf8(""))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.gridLayout_5 = QtGui.QGridLayout(self.tab)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.search_lineEdit = QtGui.QLineEdit(self.tab)
        self.search_lineEdit.setInputMask(_fromUtf8(""))
        self.search_lineEdit.setObjectName(_fromUtf8("search_lineEdit"))
        self.horizontalLayout_2.addWidget(self.search_lineEdit)
        self.search_pushButton = QtGui.QPushButton(self.tab)
        self.search_pushButton.setObjectName(_fromUtf8("search_pushButton"))
        self.horizontalLayout_2.addWidget(self.search_pushButton)
        self.search_result_label = QtGui.QLabel(self.tab)
        self.search_result_label.setText(_fromUtf8(""))
        self.search_result_label.setObjectName(_fromUtf8("search_result_label"))
        self.horizontalLayout_2.addWidget(self.search_result_label)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.gridLayout_5.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)
        self.log_tableView = QtGui.QTableView(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.log_tableView.sizePolicy().hasHeightForWidth())
        self.log_tableView.setSizePolicy(sizePolicy)
        self.log_tableView.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.log_tableView.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.log_tableView.setObjectName(_fromUtf8("log_tableView"))
        self.gridLayout_5.addWidget(self.log_tableView, 1, 0, 1, 1)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.title_label = QtGui.QLabel(Form)
        self.title_label.setGeometry(QtCore.QRect(530, 20, 216, 25))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Narrow"))
        font.setPointSize(16)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.title_label.setFont(font)
        self.title_label.setAutoFillBackground(False)
        self.title_label.setTextFormat(QtCore.Qt.AutoText)
        self.title_label.setObjectName(_fromUtf8("title_label"))
        self.layoutWidget1 = QtGui.QWidget(Form)
        self.layoutWidget1.setGeometry(QtCore.QRect(490, 620, 721, 25))
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_4.setMargin(0)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.progressBar = QtGui.QProgressBar(self.layoutWidget1)
        self.progressBar.setEnabled(True)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setTextVisible(True)
        self.progressBar.setObjectName(_fromUtf8("progressBar"))
        self.horizontalLayout_4.addWidget(self.progressBar)
        self.lcdNumber = QtGui.QLCDNumber(self.layoutWidget1)
        self.lcdNumber.setSmallDecimalPoint(False)
        self.lcdNumber.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcdNumber.setProperty("intValue", 0)
        self.lcdNumber.setObjectName(_fromUtf8("lcdNumber"))
        self.horizontalLayout_4.addWidget(self.lcdNumber)
        self.start_pushButton = QtGui.QPushButton(Form)
        self.start_pushButton.setGeometry(QtCore.QRect(1010, 20, 161, 41))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.start_pushButton.sizePolicy().hasHeightForWidth())
        self.start_pushButton.setSizePolicy(sizePolicy)
        self.start_pushButton.setObjectName(_fromUtf8("start_pushButton"))
        self.Mode4in1 = QtGui.QCheckBox(Form)
        self.Mode4in1.setGeometry(QtCore.QRect(920, 40, 67, 17))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Mode4in1.sizePolicy().hasHeightForWidth())
        self.Mode4in1.setSizePolicy(sizePolicy)
        self.Mode4in1.setObjectName(_fromUtf8("Mode4in1"))
        self.groupBox4 = QtGui.QGroupBox(Form)
        self.groupBox4.setGeometry(QtCore.QRect(10, 250, 230, 80))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox4.sizePolicy().hasHeightForWidth())
        self.groupBox4.setSizePolicy(sizePolicy)
        self.groupBox4.setObjectName(_fromUtf8("groupBox4"))
        self.layoutWidget2 = QtGui.QWidget(self.groupBox4)
        self.layoutWidget2.setGeometry(QtCore.QRect(11, 24, 211, 47))
        self.layoutWidget2.setObjectName(_fromUtf8("layoutWidget2"))
        self.gridLayout_15 = QtGui.QGridLayout(self.layoutWidget2)
        self.gridLayout_15.setMargin(0)
        self.gridLayout_15.setObjectName(_fromUtf8("gridLayout_15"))
        self.sn_lineEdit_4 = QtGui.QLineEdit(self.layoutWidget2)
        self.sn_lineEdit_4.setMaxLength(33)
        self.sn_lineEdit_4.setObjectName(_fromUtf8("sn_lineEdit_4"))
        self.gridLayout_15.addWidget(self.sn_lineEdit_4, 0, 0, 1, 1)
        self.label_4 = QtGui.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setText(_fromUtf8(""))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_15.addWidget(self.label_4, 1, 0, 1, 1)
        self.groupBox10 = QtGui.QGroupBox(Form)
        self.groupBox10.setGeometry(QtCore.QRect(250, 90, 230, 80))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox10.sizePolicy().hasHeightForWidth())
        self.groupBox10.setSizePolicy(sizePolicy)
        self.groupBox10.setObjectName(_fromUtf8("groupBox10"))
        self.layoutWidget3 = QtGui.QWidget(self.groupBox10)
        self.layoutWidget3.setGeometry(QtCore.QRect(11, 24, 211, 47))
        self.layoutWidget3.setObjectName(_fromUtf8("layoutWidget3"))
        self.gridLayout_6 = QtGui.QGridLayout(self.layoutWidget3)
        self.gridLayout_6.setMargin(0)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.sn_lineEdit_10 = QtGui.QLineEdit(self.layoutWidget3)
        self.sn_lineEdit_10.setMaxLength(33)
        self.sn_lineEdit_10.setObjectName(_fromUtf8("sn_lineEdit_10"))
        self.gridLayout_6.addWidget(self.sn_lineEdit_10, 0, 0, 1, 1)
        self.label_10 = QtGui.QLabel(self.layoutWidget3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_10.setFont(font)
        self.label_10.setText(_fromUtf8(""))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_6.addWidget(self.label_10, 1, 0, 1, 1)
        self.groupBox1 = QtGui.QGroupBox(Form)
        self.groupBox1.setGeometry(QtCore.QRect(10, 10, 230, 80))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox1.sizePolicy().hasHeightForWidth())
        self.groupBox1.setSizePolicy(sizePolicy)
        self.groupBox1.setObjectName(_fromUtf8("groupBox1"))
        self.layoutWidget4 = QtGui.QWidget(self.groupBox1)
        self.layoutWidget4.setGeometry(QtCore.QRect(12, 22, 211, 47))
        self.layoutWidget4.setObjectName(_fromUtf8("layoutWidget4"))
        self.gridLayout = QtGui.QGridLayout(self.layoutWidget4)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.sn_lineEdit_1 = QtGui.QLineEdit(self.layoutWidget4)
        self.sn_lineEdit_1.setAcceptDrops(True)
        self.sn_lineEdit_1.setText(_fromUtf8(""))
        self.sn_lineEdit_1.setMaxLength(33)
        self.sn_lineEdit_1.setObjectName(_fromUtf8("sn_lineEdit_1"))
        self.gridLayout.addWidget(self.sn_lineEdit_1, 0, 0, 1, 1)
        self.label_1 = QtGui.QLabel(self.layoutWidget4)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_1.setFont(font)
        self.label_1.setText(_fromUtf8(""))
        self.label_1.setObjectName(_fromUtf8("label_1"))
        self.gridLayout.addWidget(self.label_1, 1, 0, 1, 1)
        self.groupBox2 = QtGui.QGroupBox(Form)
        self.groupBox2.setGeometry(QtCore.QRect(10, 90, 230, 80))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox2.sizePolicy().hasHeightForWidth())
        self.groupBox2.setSizePolicy(sizePolicy)
        self.groupBox2.setObjectName(_fromUtf8("groupBox2"))
        self.layoutWidget5 = QtGui.QWidget(self.groupBox2)
        self.layoutWidget5.setGeometry(QtCore.QRect(11, 24, 211, 47))
        self.layoutWidget5.setObjectName(_fromUtf8("layoutWidget5"))
        self.gridLayout_2 = QtGui.QGridLayout(self.layoutWidget5)
        self.gridLayout_2.setMargin(0)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.sn_lineEdit_2 = QtGui.QLineEdit(self.layoutWidget5)
        self.sn_lineEdit_2.setMaxLength(33)
        self.sn_lineEdit_2.setObjectName(_fromUtf8("sn_lineEdit_2"))
        self.gridLayout_2.addWidget(self.sn_lineEdit_2, 0, 0, 1, 1)
        self.label_2 = QtGui.QLabel(self.layoutWidget5)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setText(_fromUtf8(""))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_2.addWidget(self.label_2, 1, 0, 1, 1)
        self.groupBox3 = QtGui.QGroupBox(Form)
        self.groupBox3.setGeometry(QtCore.QRect(10, 170, 230, 80))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox3.sizePolicy().hasHeightForWidth())
        self.groupBox3.setSizePolicy(sizePolicy)
        self.groupBox3.setObjectName(_fromUtf8("groupBox3"))
        self.layoutWidget6 = QtGui.QWidget(self.groupBox3)
        self.layoutWidget6.setGeometry(QtCore.QRect(11, 24, 211, 47))
        self.layoutWidget6.setObjectName(_fromUtf8("layoutWidget6"))
        self.gridLayout_8 = QtGui.QGridLayout(self.layoutWidget6)
        self.gridLayout_8.setMargin(0)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.sn_lineEdit_3 = QtGui.QLineEdit(self.layoutWidget6)
        self.sn_lineEdit_3.setMaxLength(33)
        self.sn_lineEdit_3.setObjectName(_fromUtf8("sn_lineEdit_3"))
        self.gridLayout_8.addWidget(self.sn_lineEdit_3, 0, 0, 1, 1)
        self.label_3 = QtGui.QLabel(self.layoutWidget6)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setText(_fromUtf8(""))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_8.addWidget(self.label_3, 1, 0, 1, 1)
        self.groupBox5 = QtGui.QGroupBox(Form)
        self.groupBox5.setGeometry(QtCore.QRect(10, 330, 230, 80))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox5.sizePolicy().hasHeightForWidth())
        self.groupBox5.setSizePolicy(sizePolicy)
        self.groupBox5.setObjectName(_fromUtf8("groupBox5"))
        self.layoutWidget7 = QtGui.QWidget(self.groupBox5)
        self.layoutWidget7.setGeometry(QtCore.QRect(11, 24, 211, 47))
        self.layoutWidget7.setObjectName(_fromUtf8("layoutWidget7"))
        self.gridLayout_17 = QtGui.QGridLayout(self.layoutWidget7)
        self.gridLayout_17.setMargin(0)
        self.gridLayout_17.setObjectName(_fromUtf8("gridLayout_17"))
        self.sn_lineEdit_5 = QtGui.QLineEdit(self.layoutWidget7)
        self.sn_lineEdit_5.setAcceptDrops(True)
        self.sn_lineEdit_5.setText(_fromUtf8(""))
        self.sn_lineEdit_5.setMaxLength(33)
        self.sn_lineEdit_5.setObjectName(_fromUtf8("sn_lineEdit_5"))
        self.gridLayout_17.addWidget(self.sn_lineEdit_5, 0, 0, 1, 1)
        self.label_5 = QtGui.QLabel(self.layoutWidget7)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setText(_fromUtf8(""))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_17.addWidget(self.label_5, 1, 0, 1, 1)
        self.groupBox6 = QtGui.QGroupBox(Form)
        self.groupBox6.setGeometry(QtCore.QRect(10, 410, 230, 80))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox6.sizePolicy().hasHeightForWidth())
        self.groupBox6.setSizePolicy(sizePolicy)
        self.groupBox6.setObjectName(_fromUtf8("groupBox6"))
        self.layoutWidget8 = QtGui.QWidget(self.groupBox6)
        self.layoutWidget8.setGeometry(QtCore.QRect(11, 24, 211, 47))
        self.layoutWidget8.setObjectName(_fromUtf8("layoutWidget8"))
        self.gridLayout_20 = QtGui.QGridLayout(self.layoutWidget8)
        self.gridLayout_20.setMargin(0)
        self.gridLayout_20.setObjectName(_fromUtf8("gridLayout_20"))
        self.sn_lineEdit_6 = QtGui.QLineEdit(self.layoutWidget8)
        self.sn_lineEdit_6.setMaxLength(33)
        self.sn_lineEdit_6.setObjectName(_fromUtf8("sn_lineEdit_6"))
        self.gridLayout_20.addWidget(self.sn_lineEdit_6, 0, 0, 1, 1)
        self.label_6 = QtGui.QLabel(self.layoutWidget8)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setText(_fromUtf8(""))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_20.addWidget(self.label_6, 1, 0, 1, 1)
        self.groupBox7 = QtGui.QGroupBox(Form)
        self.groupBox7.setGeometry(QtCore.QRect(10, 490, 230, 80))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox7.sizePolicy().hasHeightForWidth())
        self.groupBox7.setSizePolicy(sizePolicy)
        self.groupBox7.setObjectName(_fromUtf8("groupBox7"))
        self.layoutWidget9 = QtGui.QWidget(self.groupBox7)
        self.layoutWidget9.setGeometry(QtCore.QRect(11, 24, 211, 47))
        self.layoutWidget9.setObjectName(_fromUtf8("layoutWidget9"))
        self.gridLayout_22 = QtGui.QGridLayout(self.layoutWidget9)
        self.gridLayout_22.setMargin(0)
        self.gridLayout_22.setObjectName(_fromUtf8("gridLayout_22"))
        self.sn_lineEdit_7 = QtGui.QLineEdit(self.layoutWidget9)
        self.sn_lineEdit_7.setMaxLength(33)
        self.sn_lineEdit_7.setObjectName(_fromUtf8("sn_lineEdit_7"))
        self.gridLayout_22.addWidget(self.sn_lineEdit_7, 0, 0, 1, 1)
        self.label_7 = QtGui.QLabel(self.layoutWidget9)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setText(_fromUtf8(""))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_22.addWidget(self.label_7, 1, 0, 1, 1)
        self.groupBox8 = QtGui.QGroupBox(Form)
        self.groupBox8.setGeometry(QtCore.QRect(10, 570, 230, 80))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox8.sizePolicy().hasHeightForWidth())
        self.groupBox8.setSizePolicy(sizePolicy)
        self.groupBox8.setObjectName(_fromUtf8("groupBox8"))
        self.layoutWidget10 = QtGui.QWidget(self.groupBox8)
        self.layoutWidget10.setGeometry(QtCore.QRect(11, 24, 211, 47))
        self.layoutWidget10.setObjectName(_fromUtf8("layoutWidget10"))
        self.gridLayout_25 = QtGui.QGridLayout(self.layoutWidget10)
        self.gridLayout_25.setMargin(0)
        self.gridLayout_25.setObjectName(_fromUtf8("gridLayout_25"))
        self.sn_lineEdit_8 = QtGui.QLineEdit(self.layoutWidget10)
        self.sn_lineEdit_8.setMaxLength(33)
        self.sn_lineEdit_8.setObjectName(_fromUtf8("sn_lineEdit_8"))
        self.gridLayout_25.addWidget(self.sn_lineEdit_8, 0, 0, 1, 1)
        self.label_8 = QtGui.QLabel(self.layoutWidget10)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setText(_fromUtf8(""))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_25.addWidget(self.label_8, 1, 0, 1, 1)
        self.groupBox9 = QtGui.QGroupBox(Form)
        self.groupBox9.setGeometry(QtCore.QRect(250, 10, 230, 80))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox9.sizePolicy().hasHeightForWidth())
        self.groupBox9.setSizePolicy(sizePolicy)
        self.groupBox9.setObjectName(_fromUtf8("groupBox9"))
        self.layoutWidget11 = QtGui.QWidget(self.groupBox9)
        self.layoutWidget11.setGeometry(QtCore.QRect(11, 24, 211, 47))
        self.layoutWidget11.setObjectName(_fromUtf8("layoutWidget11"))
        self.gridLayout_18 = QtGui.QGridLayout(self.layoutWidget11)
        self.gridLayout_18.setMargin(0)
        self.gridLayout_18.setObjectName(_fromUtf8("gridLayout_18"))
        self.sn_lineEdit_9 = QtGui.QLineEdit(self.layoutWidget11)
        self.sn_lineEdit_9.setAcceptDrops(True)
        self.sn_lineEdit_9.setText(_fromUtf8(""))
        self.sn_lineEdit_9.setMaxLength(33)
        self.sn_lineEdit_9.setObjectName(_fromUtf8("sn_lineEdit_9"))
        self.gridLayout_18.addWidget(self.sn_lineEdit_9, 0, 0, 1, 1)
        self.label_9 = QtGui.QLabel(self.layoutWidget11)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setText(_fromUtf8(""))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_18.addWidget(self.label_9, 1, 0, 1, 1)
        self.groupBox11 = QtGui.QGroupBox(Form)
        self.groupBox11.setGeometry(QtCore.QRect(250, 170, 230, 80))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox11.sizePolicy().hasHeightForWidth())
        self.groupBox11.setSizePolicy(sizePolicy)
        self.groupBox11.setObjectName(_fromUtf8("groupBox11"))
        self.layoutWidget12 = QtGui.QWidget(self.groupBox11)
        self.layoutWidget12.setGeometry(QtCore.QRect(11, 24, 211, 47))
        self.layoutWidget12.setObjectName(_fromUtf8("layoutWidget12"))
        self.gridLayout_14 = QtGui.QGridLayout(self.layoutWidget12)
        self.gridLayout_14.setMargin(0)
        self.gridLayout_14.setObjectName(_fromUtf8("gridLayout_14"))
        self.sn_lineEdit_11 = QtGui.QLineEdit(self.layoutWidget12)
        self.sn_lineEdit_11.setMaxLength(33)
        self.sn_lineEdit_11.setObjectName(_fromUtf8("sn_lineEdit_11"))
        self.gridLayout_14.addWidget(self.sn_lineEdit_11, 0, 0, 1, 1)
        self.label_11 = QtGui.QLabel(self.layoutWidget12)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_11.setFont(font)
        self.label_11.setText(_fromUtf8(""))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_14.addWidget(self.label_11, 1, 0, 1, 1)
        self.groupBox12 = QtGui.QGroupBox(Form)
        self.groupBox12.setGeometry(QtCore.QRect(250, 250, 230, 80))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox12.sizePolicy().hasHeightForWidth())
        self.groupBox12.setSizePolicy(sizePolicy)
        self.groupBox12.setObjectName(_fromUtf8("groupBox12"))
        self.layoutWidget13 = QtGui.QWidget(self.groupBox12)
        self.layoutWidget13.setGeometry(QtCore.QRect(11, 24, 211, 47))
        self.layoutWidget13.setObjectName(_fromUtf8("layoutWidget13"))
        self.gridLayout_16 = QtGui.QGridLayout(self.layoutWidget13)
        self.gridLayout_16.setMargin(0)
        self.gridLayout_16.setObjectName(_fromUtf8("gridLayout_16"))
        self.sn_lineEdit_12 = QtGui.QLineEdit(self.layoutWidget13)
        self.sn_lineEdit_12.setMaxLength(33)
        self.sn_lineEdit_12.setObjectName(_fromUtf8("sn_lineEdit_12"))
        self.gridLayout_16.addWidget(self.sn_lineEdit_12, 0, 0, 1, 1)
        self.label_12 = QtGui.QLabel(self.layoutWidget13)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_12.setFont(font)
        self.label_12.setText(_fromUtf8(""))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_16.addWidget(self.label_12, 1, 0, 1, 1)
        self.groupBox13 = QtGui.QGroupBox(Form)
        self.groupBox13.setGeometry(QtCore.QRect(250, 330, 230, 80))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox13.sizePolicy().hasHeightForWidth())
        self.groupBox13.setSizePolicy(sizePolicy)
        self.groupBox13.setObjectName(_fromUtf8("groupBox13"))
        self.layoutWidget14 = QtGui.QWidget(self.groupBox13)
        self.layoutWidget14.setGeometry(QtCore.QRect(11, 24, 211, 47))
        self.layoutWidget14.setObjectName(_fromUtf8("layoutWidget14"))
        self.gridLayout_19 = QtGui.QGridLayout(self.layoutWidget14)
        self.gridLayout_19.setMargin(0)
        self.gridLayout_19.setObjectName(_fromUtf8("gridLayout_19"))
        self.sn_lineEdit_13 = QtGui.QLineEdit(self.layoutWidget14)
        self.sn_lineEdit_13.setAcceptDrops(True)
        self.sn_lineEdit_13.setText(_fromUtf8(""))
        self.sn_lineEdit_13.setMaxLength(33)
        self.sn_lineEdit_13.setObjectName(_fromUtf8("sn_lineEdit_13"))
        self.gridLayout_19.addWidget(self.sn_lineEdit_13, 0, 0, 1, 1)
        self.label_13 = QtGui.QLabel(self.layoutWidget14)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_13.setFont(font)
        self.label_13.setText(_fromUtf8(""))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout_19.addWidget(self.label_13, 1, 0, 1, 1)
        self.groupBox14 = QtGui.QGroupBox(Form)
        self.groupBox14.setGeometry(QtCore.QRect(250, 410, 230, 80))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox14.sizePolicy().hasHeightForWidth())
        self.groupBox14.setSizePolicy(sizePolicy)
        self.groupBox14.setObjectName(_fromUtf8("groupBox14"))
        self.layoutWidget15 = QtGui.QWidget(self.groupBox14)
        self.layoutWidget15.setGeometry(QtCore.QRect(11, 24, 211, 47))
        self.layoutWidget15.setObjectName(_fromUtf8("layoutWidget15"))
        self.gridLayout_21 = QtGui.QGridLayout(self.layoutWidget15)
        self.gridLayout_21.setMargin(0)
        self.gridLayout_21.setObjectName(_fromUtf8("gridLayout_21"))
        self.sn_lineEdit_14 = QtGui.QLineEdit(self.layoutWidget15)
        self.sn_lineEdit_14.setMaxLength(33)
        self.sn_lineEdit_14.setObjectName(_fromUtf8("sn_lineEdit_14"))
        self.gridLayout_21.addWidget(self.sn_lineEdit_14, 0, 0, 1, 1)
        self.label_14 = QtGui.QLabel(self.layoutWidget15)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_14.setFont(font)
        self.label_14.setText(_fromUtf8(""))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout_21.addWidget(self.label_14, 1, 0, 1, 1)
        self.groupBox15 = QtGui.QGroupBox(Form)
        self.groupBox15.setGeometry(QtCore.QRect(250, 490, 230, 80))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox15.sizePolicy().hasHeightForWidth())
        self.groupBox15.setSizePolicy(sizePolicy)
        self.groupBox15.setObjectName(_fromUtf8("groupBox15"))
        self.layoutWidget16 = QtGui.QWidget(self.groupBox15)
        self.layoutWidget16.setGeometry(QtCore.QRect(11, 24, 211, 47))
        self.layoutWidget16.setObjectName(_fromUtf8("layoutWidget16"))
        self.gridLayout_23 = QtGui.QGridLayout(self.layoutWidget16)
        self.gridLayout_23.setMargin(0)
        self.gridLayout_23.setObjectName(_fromUtf8("gridLayout_23"))
        self.sn_lineEdit_15 = QtGui.QLineEdit(self.layoutWidget16)
        self.sn_lineEdit_15.setMaxLength(33)
        self.sn_lineEdit_15.setObjectName(_fromUtf8("sn_lineEdit_15"))
        self.gridLayout_23.addWidget(self.sn_lineEdit_15, 0, 0, 1, 1)
        self.label_15 = QtGui.QLabel(self.layoutWidget16)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_15.setFont(font)
        self.label_15.setText(_fromUtf8(""))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.gridLayout_23.addWidget(self.label_15, 1, 0, 1, 1)
        self.groupBox16 = QtGui.QGroupBox(Form)
        self.groupBox16.setGeometry(QtCore.QRect(250, 570, 230, 80))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox16.sizePolicy().hasHeightForWidth())
        self.groupBox16.setSizePolicy(sizePolicy)
        self.groupBox16.setObjectName(_fromUtf8("groupBox16"))
        self.layoutWidget17 = QtGui.QWidget(self.groupBox16)
        self.layoutWidget17.setGeometry(QtCore.QRect(11, 24, 211, 47))
        self.layoutWidget17.setObjectName(_fromUtf8("layoutWidget17"))
        self.gridLayout_24 = QtGui.QGridLayout(self.layoutWidget17)
        self.gridLayout_24.setMargin(0)
        self.gridLayout_24.setObjectName(_fromUtf8("gridLayout_24"))
        self.sn_lineEdit_16 = QtGui.QLineEdit(self.layoutWidget17)
        self.sn_lineEdit_16.setMaxLength(33)
        self.sn_lineEdit_16.setObjectName(_fromUtf8("sn_lineEdit_16"))
        self.gridLayout_24.addWidget(self.sn_lineEdit_16, 0, 0, 1, 1)
        self.label_16 = QtGui.QLabel(self.layoutWidget17)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_16.setFont(font)
        self.label_16.setText(_fromUtf8(""))
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.gridLayout_24.addWidget(self.label_16, 1, 0, 1, 1)

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(2)
        QtCore.QObject.connect(self.checkBox, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.submit_pushButton.setEnabled)
        QtCore.QObject.connect(self.start_pushButton, QtCore.SIGNAL(_fromUtf8("clicked()")), self.info_textBrowser.clear)
        QtCore.QObject.connect(self.sn_lineEdit_1, QtCore.SIGNAL(_fromUtf8("returnPressed()")), self.sn_lineEdit_2.clear)
        QtCore.QObject.connect(self.sn_lineEdit_2, QtCore.SIGNAL(_fromUtf8("returnPressed()")), self.sn_lineEdit_3.clear)
        QtCore.QObject.connect(self.sn_lineEdit_3, QtCore.SIGNAL(_fromUtf8("returnPressed()")), self.sn_lineEdit_4.clear)
        QtCore.QObject.connect(self.sn_lineEdit_4, QtCore.SIGNAL(_fromUtf8("returnPressed()")), self.sn_lineEdit_5.clear)
        QtCore.QObject.connect(self.sn_lineEdit_5, QtCore.SIGNAL(_fromUtf8("returnPressed()")), self.sn_lineEdit_6.clear)
        QtCore.QObject.connect(self.sn_lineEdit_6, QtCore.SIGNAL(_fromUtf8("returnPressed()")), self.sn_lineEdit_7.clear)
        QtCore.QObject.connect(self.sn_lineEdit_7, QtCore.SIGNAL(_fromUtf8("returnPressed()")), self.sn_lineEdit_8.clear)
        QtCore.QObject.connect(self.sn_lineEdit_8, QtCore.SIGNAL(_fromUtf8("returnPressed()")), self.sn_lineEdit_9.clear)
        QtCore.QObject.connect(self.sn_lineEdit_9, QtCore.SIGNAL(_fromUtf8("returnPressed()")), self.sn_lineEdit_10.clear)
        QtCore.QObject.connect(self.sn_lineEdit_10, QtCore.SIGNAL(_fromUtf8("returnPressed()")), self.sn_lineEdit_11.clear)
        QtCore.QObject.connect(self.sn_lineEdit_11, QtCore.SIGNAL(_fromUtf8("returnPressed()")), self.sn_lineEdit_12.clear)
        QtCore.QObject.connect(self.sn_lineEdit_12, QtCore.SIGNAL(_fromUtf8("returnPressed()")), self.sn_lineEdit_13.clear)
        QtCore.QObject.connect(self.sn_lineEdit_13, QtCore.SIGNAL(_fromUtf8("returnPressed()")), self.sn_lineEdit_14.clear)
        QtCore.QObject.connect(self.sn_lineEdit_14, QtCore.SIGNAL(_fromUtf8("returnPressed()")), self.sn_lineEdit_15.clear)
        QtCore.QObject.connect(self.sn_lineEdit_15, QtCore.SIGNAL(_fromUtf8("returnPressed()")), self.sn_lineEdit_16.clear)
        QtCore.QObject.connect(self.sn_lineEdit_1, QtCore.SIGNAL(_fromUtf8("returnPressed()")), self.sn_lineEdit_2.setFocus)
        QtCore.QObject.connect(self.sn_lineEdit_2, QtCore.SIGNAL(_fromUtf8("returnPressed()")), self.sn_lineEdit_3.setFocus)
        QtCore.QObject.connect(self.sn_lineEdit_3, QtCore.SIGNAL(_fromUtf8("returnPressed()")), self.sn_lineEdit_4.setFocus)
        QtCore.QObject.connect(self.sn_lineEdit_4, QtCore.SIGNAL(_fromUtf8("returnPressed()")), self.sn_lineEdit_5.setFocus)
        QtCore.QObject.connect(self.sn_lineEdit_5, QtCore.SIGNAL(_fromUtf8("returnPressed()")), self.sn_lineEdit_6.setFocus)
        QtCore.QObject.connect(self.sn_lineEdit_6, QtCore.SIGNAL(_fromUtf8("returnPressed()")), self.sn_lineEdit_7.setFocus)
        QtCore.QObject.connect(self.sn_lineEdit_7, QtCore.SIGNAL(_fromUtf8("returnPressed()")), self.sn_lineEdit_8.setFocus)
        QtCore.QObject.connect(self.sn_lineEdit_8, QtCore.SIGNAL(_fromUtf8("returnPressed()")), self.sn_lineEdit_9.setFocus)
        QtCore.QObject.connect(self.sn_lineEdit_9, QtCore.SIGNAL(_fromUtf8("returnPressed()")), self.sn_lineEdit_10.setFocus)
        QtCore.QObject.connect(self.sn_lineEdit_10, QtCore.SIGNAL(_fromUtf8("returnPressed()")), self.sn_lineEdit_11.setFocus)
        QtCore.QObject.connect(self.sn_lineEdit_11, QtCore.SIGNAL(_fromUtf8("returnPressed()")), self.sn_lineEdit_12.setFocus)
        QtCore.QObject.connect(self.sn_lineEdit_12, QtCore.SIGNAL(_fromUtf8("returnPressed()")), self.sn_lineEdit_13.setFocus)
        QtCore.QObject.connect(self.sn_lineEdit_13, QtCore.SIGNAL(_fromUtf8("returnPressed()")), self.sn_lineEdit_14.setFocus)
        QtCore.QObject.connect(self.sn_lineEdit_14, QtCore.SIGNAL(_fromUtf8("returnPressed()")), self.sn_lineEdit_15.setFocus)
        QtCore.QObject.connect(self.sn_lineEdit_15, QtCore.SIGNAL(_fromUtf8("returnPressed()")), self.sn_lineEdit_16.setFocus)
        QtCore.QObject.connect(self.CablelineEdit_1, QtCore.SIGNAL(_fromUtf8("returnPressed()")), self.CablelineEdit_2.clear)
        QtCore.QObject.connect(self.CablelineEdit_2, QtCore.SIGNAL(_fromUtf8("returnPressed()")), self.CablelineEdit_3.clear)
        QtCore.QObject.connect(self.CablelineEdit_3, QtCore.SIGNAL(_fromUtf8("returnPressed()")), self.CablelineEdit_4.clear)
        QtCore.QObject.connect(self.CablelineEdit_4, QtCore.SIGNAL(_fromUtf8("returnPressed()")), self.CablelineEdit_5.clear)
        QtCore.QObject.connect(self.CablelineEdit_5, QtCore.SIGNAL(_fromUtf8("returnPressed()")), self.CablelineEdit_6.clear)
        QtCore.QObject.connect(self.CablelineEdit_6, QtCore.SIGNAL(_fromUtf8("returnPressed()")), self.CablelineEdit_7.clear)
        QtCore.QObject.connect(self.CablelineEdit_7, QtCore.SIGNAL(_fromUtf8("returnPressed()")), self.CablelineEdit_8.clear)
        QtCore.QObject.connect(self.CablelineEdit_8, QtCore.SIGNAL(_fromUtf8("returnPressed()")), self.CablelineEdit_9.clear)
        QtCore.QObject.connect(self.CablelineEdit_9, QtCore.SIGNAL(_fromUtf8("returnPressed()")), self.CablelineEdit_10.clear)
        QtCore.QObject.connect(self.CablelineEdit_10, QtCore.SIGNAL(_fromUtf8("returnPressed()")), self.CablelineEdit_11.clear)
        QtCore.QObject.connect(self.CablelineEdit_11, QtCore.SIGNAL(_fromUtf8("returnPressed()")), self.CablelineEdit_12.clear)
        QtCore.QObject.connect(self.CablelineEdit_12, QtCore.SIGNAL(_fromUtf8("returnPressed()")), self.CablelineEdit_13.clear)
        QtCore.QObject.connect(self.CablelineEdit_13, QtCore.SIGNAL(_fromUtf8("returnPressed()")), self.CablelineEdit_14.clear)
        QtCore.QObject.connect(self.CablelineEdit_14, QtCore.SIGNAL(_fromUtf8("returnPressed()")), self.CablelineEdit_15.clear)
        QtCore.QObject.connect(self.CablelineEdit_15, QtCore.SIGNAL(_fromUtf8("returnPressed()")), self.CablelineEdit_16.clear)
        QtCore.QObject.connect(self.CablelineEdit_1, QtCore.SIGNAL(_fromUtf8("returnPressed()")), self.CablelineEdit_2.setFocus)
        QtCore.QObject.connect(self.CablelineEdit_2, QtCore.SIGNAL(_fromUtf8("returnPressed()")), self.CablelineEdit_3.setFocus)
        QtCore.QObject.connect(self.CablelineEdit_3, QtCore.SIGNAL(_fromUtf8("returnPressed()")), self.CablelineEdit_4.setFocus)
        QtCore.QObject.connect(self.CablelineEdit_4, QtCore.SIGNAL(_fromUtf8("returnPressed()")), self.CablelineEdit_5.setFocus)
        QtCore.QObject.connect(self.CablelineEdit_5, QtCore.SIGNAL(_fromUtf8("returnPressed()")), self.CablelineEdit_6.setFocus)
        QtCore.QObject.connect(self.CablelineEdit_6, QtCore.SIGNAL(_fromUtf8("returnPressed()")), self.CablelineEdit_7.setFocus)
        QtCore.QObject.connect(self.CablelineEdit_7, QtCore.SIGNAL(_fromUtf8("returnPressed()")), self.CablelineEdit_8.setFocus)
        QtCore.QObject.connect(self.CablelineEdit_8, QtCore.SIGNAL(_fromUtf8("returnPressed()")), self.CablelineEdit_9.setFocus)
        QtCore.QObject.connect(self.CablelineEdit_9, QtCore.SIGNAL(_fromUtf8("returnPressed()")), self.CablelineEdit_10.setFocus)
        QtCore.QObject.connect(self.CablelineEdit_10, QtCore.SIGNAL(_fromUtf8("returnPressed()")), self.CablelineEdit_11.setFocus)
        QtCore.QObject.connect(self.CablelineEdit_11, QtCore.SIGNAL(_fromUtf8("returnPressed()")), self.CablelineEdit_12.setFocus)
        QtCore.QObject.connect(self.CablelineEdit_12, QtCore.SIGNAL(_fromUtf8("returnPressed()")), self.CablelineEdit_13.setFocus)
        QtCore.QObject.connect(self.CablelineEdit_13, QtCore.SIGNAL(_fromUtf8("returnPressed()")), self.CablelineEdit_14.setFocus)
        QtCore.QObject.connect(self.CablelineEdit_14, QtCore.SIGNAL(_fromUtf8("returnPressed()")), self.CablelineEdit_15.setFocus)
        QtCore.QObject.connect(self.CablelineEdit_15, QtCore.SIGNAL(_fromUtf8("returnPressed()")), self.CablelineEdit_16.setFocus)
        QtCore.QObject.connect(self.Mode4in1, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.groupBox2.setDisabled)
        QtCore.QObject.connect(self.Mode4in1, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.groupBox3.setDisabled)
        QtCore.QObject.connect(self.Mode4in1, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.groupBox4.setDisabled)
        QtCore.QObject.connect(self.Mode4in1, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.groupBox6.setDisabled)
        QtCore.QObject.connect(self.Mode4in1, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.groupBox7.setDisabled)
        QtCore.QObject.connect(self.Mode4in1, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.groupBox8.setDisabled)
        QtCore.QObject.connect(self.Mode4in1, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.groupBox10.setDisabled)
        QtCore.QObject.connect(self.Mode4in1, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.groupBox11.setDisabled)
        QtCore.QObject.connect(self.Mode4in1, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.groupBox12.setDisabled)
        QtCore.QObject.connect(self.Mode4in1, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.groupBox14.setDisabled)
        QtCore.QObject.connect(self.Mode4in1, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.groupBox15.setDisabled)
        QtCore.QObject.connect(self.Mode4in1, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.groupBox16.setDisabled)
        QtCore.QObject.connect(self.Mode4in1, QtCore.SIGNAL(_fromUtf8("clicked()")), self.sn_lineEdit_2.clear)
        QtCore.QObject.connect(self.Mode4in1, QtCore.SIGNAL(_fromUtf8("clicked()")), self.sn_lineEdit_3.clear)
        QtCore.QObject.connect(self.Mode4in1, QtCore.SIGNAL(_fromUtf8("clicked()")), self.sn_lineEdit_4.clear)
        QtCore.QObject.connect(self.Mode4in1, QtCore.SIGNAL(_fromUtf8("clicked()")), self.sn_lineEdit_6.clear)
        QtCore.QObject.connect(self.Mode4in1, QtCore.SIGNAL(_fromUtf8("clicked()")), self.sn_lineEdit_7.clear)
        QtCore.QObject.connect(self.Mode4in1, QtCore.SIGNAL(_fromUtf8("clicked()")), self.sn_lineEdit_8.clear)
        QtCore.QObject.connect(self.Mode4in1, QtCore.SIGNAL(_fromUtf8("clicked()")), self.sn_lineEdit_10.clear)
        QtCore.QObject.connect(self.Mode4in1, QtCore.SIGNAL(_fromUtf8("clicked()")), self.sn_lineEdit_11.clear)
        QtCore.QObject.connect(self.Mode4in1, QtCore.SIGNAL(_fromUtf8("clicked()")), self.sn_lineEdit_12.clear)
        QtCore.QObject.connect(self.Mode4in1, QtCore.SIGNAL(_fromUtf8("clicked()")), self.sn_lineEdit_14.clear)
        QtCore.QObject.connect(self.Mode4in1, QtCore.SIGNAL(_fromUtf8("clicked()")), self.sn_lineEdit_15.clear)
        QtCore.QObject.connect(self.Mode4in1, QtCore.SIGNAL(_fromUtf8("clicked()")), self.sn_lineEdit_16.clear)
        QtCore.QObject.connect(self.Mode4in1, QtCore.SIGNAL(_fromUtf8("clicked()")), self.CablelineEdit_2.clear)
        QtCore.QObject.connect(self.Mode4in1, QtCore.SIGNAL(_fromUtf8("clicked()")), self.CablelineEdit_3.clear)
        QtCore.QObject.connect(self.Mode4in1, QtCore.SIGNAL(_fromUtf8("clicked()")), self.CablelineEdit_4.clear)
        QtCore.QObject.connect(self.Mode4in1, QtCore.SIGNAL(_fromUtf8("clicked()")), self.CablelineEdit_6.clear)
        QtCore.QObject.connect(self.Mode4in1, QtCore.SIGNAL(_fromUtf8("clicked()")), self.CablelineEdit_7.clear)
        QtCore.QObject.connect(self.Mode4in1, QtCore.SIGNAL(_fromUtf8("clicked()")), self.CablelineEdit_8.clear)
        QtCore.QObject.connect(self.Mode4in1, QtCore.SIGNAL(_fromUtf8("clicked()")), self.CablelineEdit_10.clear)
        QtCore.QObject.connect(self.Mode4in1, QtCore.SIGNAL(_fromUtf8("clicked()")), self.CablelineEdit_11.clear)
        QtCore.QObject.connect(self.Mode4in1, QtCore.SIGNAL(_fromUtf8("clicked()")), self.CablelineEdit_12.clear)
        QtCore.QObject.connect(self.Mode4in1, QtCore.SIGNAL(_fromUtf8("clicked()")), self.CablelineEdit_14.clear)
        QtCore.QObject.connect(self.Mode4in1, QtCore.SIGNAL(_fromUtf8("clicked()")), self.CablelineEdit_15.clear)
        QtCore.QObject.connect(self.Mode4in1, QtCore.SIGNAL(_fromUtf8("clicked()")), self.CablelineEdit_16.clear)
        QtCore.QObject.connect(self.BatterylineEdit_1, QtCore.SIGNAL(_fromUtf8("returnPressed()")), self.BatterylineEdit_2.clear)
        QtCore.QObject.connect(self.BatterylineEdit_2, QtCore.SIGNAL(_fromUtf8("returnPressed()")), self.BatterylineEdit_3.clear)
        QtCore.QObject.connect(self.BatterylineEdit_3, QtCore.SIGNAL(_fromUtf8("returnPressed()")), self.BatterylineEdit_4.clear)
        QtCore.QObject.connect(self.BatterylineEdit_4, QtCore.SIGNAL(_fromUtf8("returnPressed()")), self.BatterylineEdit_5.clear)
        QtCore.QObject.connect(self.BatterylineEdit_5, QtCore.SIGNAL(_fromUtf8("returnPressed()")), self.BatterylineEdit_6.clear)
        QtCore.QObject.connect(self.BatterylineEdit_6, QtCore.SIGNAL(_fromUtf8("returnPressed()")), self.BatterylineEdit_7.clear)
        QtCore.QObject.connect(self.BatterylineEdit_7, QtCore.SIGNAL(_fromUtf8("returnPressed()")), self.BatterylineEdit_8.clear)
        QtCore.QObject.connect(self.BatterylineEdit_8, QtCore.SIGNAL(_fromUtf8("returnPressed()")), self.BatterylineEdit_9.clear)
        QtCore.QObject.connect(self.BatterylineEdit_9, QtCore.SIGNAL(_fromUtf8("returnPressed()")), self.BatterylineEdit_10.clear)
        QtCore.QObject.connect(self.BatterylineEdit_10, QtCore.SIGNAL(_fromUtf8("returnPressed()")), self.BatterylineEdit_11.clear)
        QtCore.QObject.connect(self.BatterylineEdit_11, QtCore.SIGNAL(_fromUtf8("returnPressed()")), self.BatterylineEdit_12.clear)
        QtCore.QObject.connect(self.BatterylineEdit_12, QtCore.SIGNAL(_fromUtf8("returnPressed()")), self.BatterylineEdit_13.clear)
        QtCore.QObject.connect(self.BatterylineEdit_13, QtCore.SIGNAL(_fromUtf8("returnPressed()")), self.BatterylineEdit_14.clear)
        QtCore.QObject.connect(self.BatterylineEdit_14, QtCore.SIGNAL(_fromUtf8("returnPressed()")), self.BatterylineEdit_15.clear)
        QtCore.QObject.connect(self.BatterylineEdit_15, QtCore.SIGNAL(_fromUtf8("returnPressed()")), self.BatterylineEdit_16.clear)
        QtCore.QObject.connect(self.BatterylineEdit_1, QtCore.SIGNAL(_fromUtf8("returnPressed()")), self.BatterylineEdit_2.setFocus)
        QtCore.QObject.connect(self.BatterylineEdit_2, QtCore.SIGNAL(_fromUtf8("returnPressed()")), self.BatterylineEdit_3.setFocus)
        QtCore.QObject.connect(self.BatterylineEdit_3, QtCore.SIGNAL(_fromUtf8("returnPressed()")), self.BatterylineEdit_4.setFocus)
        QtCore.QObject.connect(self.BatterylineEdit_4, QtCore.SIGNAL(_fromUtf8("returnPressed()")), self.BatterylineEdit_5.setFocus)
        QtCore.QObject.connect(self.BatterylineEdit_5, QtCore.SIGNAL(_fromUtf8("returnPressed()")), self.BatterylineEdit_6.setFocus)
        QtCore.QObject.connect(self.BatterylineEdit_6, QtCore.SIGNAL(_fromUtf8("returnPressed()")), self.BatterylineEdit_7.setFocus)
        QtCore.QObject.connect(self.BatterylineEdit_7, QtCore.SIGNAL(_fromUtf8("returnPressed()")), self.BatterylineEdit_8.setFocus)
        QtCore.QObject.connect(self.BatterylineEdit_8, QtCore.SIGNAL(_fromUtf8("returnPressed()")), self.BatterylineEdit_9.setFocus)
        QtCore.QObject.connect(self.BatterylineEdit_9, QtCore.SIGNAL(_fromUtf8("returnPressed()")), self.BatterylineEdit_10.setFocus)
        QtCore.QObject.connect(self.BatterylineEdit_10, QtCore.SIGNAL(_fromUtf8("returnPressed()")), self.BatterylineEdit_11.setFocus)
        QtCore.QObject.connect(self.BatterylineEdit_11, QtCore.SIGNAL(_fromUtf8("returnPressed()")), self.BatterylineEdit_12.setFocus)
        QtCore.QObject.connect(self.BatterylineEdit_12, QtCore.SIGNAL(_fromUtf8("returnPressed()")), self.BatterylineEdit_13.setFocus)
        QtCore.QObject.connect(self.BatterylineEdit_13, QtCore.SIGNAL(_fromUtf8("returnPressed()")), self.BatterylineEdit_14.setFocus)
        QtCore.QObject.connect(self.BatterylineEdit_14, QtCore.SIGNAL(_fromUtf8("returnPressed()")), self.BatterylineEdit_15.setFocus)
        QtCore.QObject.connect(self.BatterylineEdit_15, QtCore.SIGNAL(_fromUtf8("returnPressed()")), self.BatterylineEdit_16.setFocus)
        QtCore.QObject.connect(self.Mode4in1, QtCore.SIGNAL(_fromUtf8("clicked()")), self.BatterylineEdit_2.clear)
        QtCore.QObject.connect(self.Mode4in1, QtCore.SIGNAL(_fromUtf8("clicked()")), self.BatterylineEdit_3.clear)
        QtCore.QObject.connect(self.Mode4in1, QtCore.SIGNAL(_fromUtf8("clicked()")), self.BatterylineEdit_4.clear)
        QtCore.QObject.connect(self.Mode4in1, QtCore.SIGNAL(_fromUtf8("clicked()")), self.BatterylineEdit_6.clear)
        QtCore.QObject.connect(self.Mode4in1, QtCore.SIGNAL(_fromUtf8("clicked()")), self.BatterylineEdit_7.clear)
        QtCore.QObject.connect(self.Mode4in1, QtCore.SIGNAL(_fromUtf8("clicked()")), self.BatterylineEdit_8.clear)
        QtCore.QObject.connect(self.Mode4in1, QtCore.SIGNAL(_fromUtf8("clicked()")), self.BatterylineEdit_10.clear)
        QtCore.QObject.connect(self.Mode4in1, QtCore.SIGNAL(_fromUtf8("clicked()")), self.BatterylineEdit_11.clear)
        QtCore.QObject.connect(self.Mode4in1, QtCore.SIGNAL(_fromUtf8("clicked()")), self.BatterylineEdit_12.clear)
        QtCore.QObject.connect(self.Mode4in1, QtCore.SIGNAL(_fromUtf8("clicked()")), self.BatterylineEdit_14.clear)
        QtCore.QObject.connect(self.Mode4in1, QtCore.SIGNAL(_fromUtf8("clicked()")), self.BatterylineEdit_15.clear)
        QtCore.QObject.connect(self.Mode4in1, QtCore.SIGNAL(_fromUtf8("clicked()")), self.BatterylineEdit_16.clear)
        QtCore.QObject.connect(self.Mode4in1, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.CablelineEdit_2.setDisabled)
        QtCore.QObject.connect(self.Mode4in1, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.CablelineEdit_3.setDisabled)
        QtCore.QObject.connect(self.Mode4in1, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.CablelineEdit_4.setDisabled)
        QtCore.QObject.connect(self.Mode4in1, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.CablelineEdit_6.setDisabled)
        QtCore.QObject.connect(self.Mode4in1, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.CablelineEdit_7.setDisabled)
        QtCore.QObject.connect(self.Mode4in1, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.CablelineEdit_8.setDisabled)
        QtCore.QObject.connect(self.Mode4in1, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.CablelineEdit_10.setDisabled)
        QtCore.QObject.connect(self.Mode4in1, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.CablelineEdit_11.setDisabled)
        QtCore.QObject.connect(self.Mode4in1, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.CablelineEdit_12.setDisabled)
        QtCore.QObject.connect(self.Mode4in1, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.CablelineEdit_14.setDisabled)
        QtCore.QObject.connect(self.Mode4in1, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.CablelineEdit_15.setDisabled)
        QtCore.QObject.connect(self.Mode4in1, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.CablelineEdit_16.setDisabled)
        QtCore.QObject.connect(self.Mode4in1, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.BatterylineEdit_2.setDisabled)
        QtCore.QObject.connect(self.Mode4in1, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.BatterylineEdit_3.setDisabled)
        QtCore.QObject.connect(self.Mode4in1, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.BatterylineEdit_4.setDisabled)
        QtCore.QObject.connect(self.Mode4in1, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.BatterylineEdit_6.setDisabled)
        QtCore.QObject.connect(self.Mode4in1, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.BatterylineEdit_7.setDisabled)
        QtCore.QObject.connect(self.Mode4in1, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.BatterylineEdit_8.setDisabled)
        QtCore.QObject.connect(self.Mode4in1, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.BatterylineEdit_10.setDisabled)
        QtCore.QObject.connect(self.Mode4in1, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.BatterylineEdit_11.setDisabled)
        QtCore.QObject.connect(self.Mode4in1, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.BatterylineEdit_12.setDisabled)
        QtCore.QObject.connect(self.Mode4in1, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.BatterylineEdit_14.setDisabled)
        QtCore.QObject.connect(self.Mode4in1, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.BatterylineEdit_15.setDisabled)
        QtCore.QObject.connect(self.Mode4in1, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.BatterylineEdit_16.setDisabled)
        QtCore.QMetaObject.connectSlotsByName(Form)
        Form.setTabOrder(self.tabWidget, self.Mode4in1)
        Form.setTabOrder(self.Mode4in1, self.start_pushButton)
        Form.setTabOrder(self.start_pushButton, self.sn_lineEdit_1)
        Form.setTabOrder(self.sn_lineEdit_1, self.sn_lineEdit_2)
        Form.setTabOrder(self.sn_lineEdit_2, self.sn_lineEdit_3)
        Form.setTabOrder(self.sn_lineEdit_3, self.sn_lineEdit_4)
        Form.setTabOrder(self.sn_lineEdit_4, self.sn_lineEdit_5)
        Form.setTabOrder(self.sn_lineEdit_5, self.sn_lineEdit_6)
        Form.setTabOrder(self.sn_lineEdit_6, self.sn_lineEdit_7)
        Form.setTabOrder(self.sn_lineEdit_7, self.sn_lineEdit_8)
        Form.setTabOrder(self.sn_lineEdit_8, self.sn_lineEdit_9)
        Form.setTabOrder(self.sn_lineEdit_9, self.sn_lineEdit_10)
        Form.setTabOrder(self.sn_lineEdit_10, self.sn_lineEdit_11)
        Form.setTabOrder(self.sn_lineEdit_11, self.sn_lineEdit_12)
        Form.setTabOrder(self.sn_lineEdit_12, self.sn_lineEdit_13)
        Form.setTabOrder(self.sn_lineEdit_13, self.sn_lineEdit_14)
        Form.setTabOrder(self.sn_lineEdit_14, self.sn_lineEdit_15)
        Form.setTabOrder(self.sn_lineEdit_15, self.sn_lineEdit_16)
        Form.setTabOrder(self.sn_lineEdit_16, self.CablelineEdit_1)
        Form.setTabOrder(self.CablelineEdit_1, self.CablelineEdit_2)
        Form.setTabOrder(self.CablelineEdit_2, self.CablelineEdit_3)
        Form.setTabOrder(self.CablelineEdit_3, self.CablelineEdit_4)
        Form.setTabOrder(self.CablelineEdit_4, self.CablelineEdit_5)
        Form.setTabOrder(self.CablelineEdit_5, self.CablelineEdit_6)
        Form.setTabOrder(self.CablelineEdit_6, self.CablelineEdit_7)
        Form.setTabOrder(self.CablelineEdit_7, self.CablelineEdit_8)
        Form.setTabOrder(self.CablelineEdit_8, self.CablelineEdit_9)
        Form.setTabOrder(self.CablelineEdit_9, self.CablelineEdit_10)
        Form.setTabOrder(self.CablelineEdit_10, self.CablelineEdit_11)
        Form.setTabOrder(self.CablelineEdit_11, self.CablelineEdit_12)
        Form.setTabOrder(self.CablelineEdit_12, self.CablelineEdit_13)
        Form.setTabOrder(self.CablelineEdit_13, self.CablelineEdit_14)
        Form.setTabOrder(self.CablelineEdit_14, self.CablelineEdit_15)
        Form.setTabOrder(self.CablelineEdit_15, self.CablelineEdit_16)
        Form.setTabOrder(self.CablelineEdit_16, self.BatterylineEdit_1)
        Form.setTabOrder(self.BatterylineEdit_1, self.BatterylineEdit_2)
        Form.setTabOrder(self.BatterylineEdit_2, self.BatterylineEdit_3)
        Form.setTabOrder(self.BatterylineEdit_3, self.BatterylineEdit_4)
        Form.setTabOrder(self.BatterylineEdit_4, self.BatterylineEdit_5)
        Form.setTabOrder(self.BatterylineEdit_5, self.BatterylineEdit_6)
        Form.setTabOrder(self.BatterylineEdit_6, self.BatterylineEdit_7)
        Form.setTabOrder(self.BatterylineEdit_7, self.BatterylineEdit_8)
        Form.setTabOrder(self.BatterylineEdit_8, self.BatterylineEdit_9)
        Form.setTabOrder(self.BatterylineEdit_9, self.BatterylineEdit_10)
        Form.setTabOrder(self.BatterylineEdit_10, self.BatterylineEdit_11)
        Form.setTabOrder(self.BatterylineEdit_11, self.BatterylineEdit_12)
        Form.setTabOrder(self.BatterylineEdit_12, self.BatterylineEdit_13)
        Form.setTabOrder(self.BatterylineEdit_13, self.BatterylineEdit_14)
        Form.setTabOrder(self.BatterylineEdit_14, self.BatterylineEdit_15)
        Form.setTabOrder(self.BatterylineEdit_15, self.BatterylineEdit_16)
        Form.setTabOrder(self.BatterylineEdit_16, self.info_textBrowser)
        Form.setTabOrder(self.info_textBrowser, self.radioButton)
        Form.setTabOrder(self.radioButton, self.radioButton_2)
        Form.setTabOrder(self.radioButton_2, self.radioButton_3)
        Form.setTabOrder(self.radioButton_3, self.partNum_comboBox)
        Form.setTabOrder(self.partNum_comboBox, self.revision_comboBox)
        Form.setTabOrder(self.revision_comboBox, self.test_item_tableView)
        Form.setTabOrder(self.test_item_tableView, self.submit_pushButton)
        Form.setTabOrder(self.submit_pushButton, self.checkBox)
        Form.setTabOrder(self.checkBox, self.search_lineEdit)
        Form.setTabOrder(self.search_lineEdit, self.search_pushButton)
        Form.setTabOrder(self.search_pushButton, self.log_tableView)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "AGIGA-UFT-TEST", None))
        self.CablelineEdit_16.setPlaceholderText(_translate("Form", "Cable_SN_16", None))
        self.CablelineEdit_10.setPlaceholderText(_translate("Form", "Cable_SN_10", None))
        self.CablelineEdit_5.setPlaceholderText(_translate("Form", "Cable_SN_5", None))
        self.CablelineEdit_9.setPlaceholderText(_translate("Form", "Cable_SN_9", None))
        self.CablelineEdit_11.setPlaceholderText(_translate("Form", "Cable_SN_11", None))
        self.CablelineEdit_14.setPlaceholderText(_translate("Form", "Cable_SN_14", None))
        self.CablelineEdit_6.setPlaceholderText(_translate("Form", "Cable_SN_6", None))
        self.CablelineEdit_15.setPlaceholderText(_translate("Form", "Cable_SN_15", None))
        self.CablelineEdit_1.setPlaceholderText(_translate("Form", "Cable_SN_1", None))
        self.CablelineEdit_12.setPlaceholderText(_translate("Form", "Cable_SN_12", None))
        self.CablelineEdit_4.setPlaceholderText(_translate("Form", "Cable_SN_4", None))
        self.CablelineEdit_7.setPlaceholderText(_translate("Form", "Cable_SN_7", None))
        self.CablelineEdit_13.setPlaceholderText(_translate("Form", "Cable_SN_13", None))
        self.CablelineEdit_2.setPlaceholderText(_translate("Form", "Cable_SN_2", None))
        self.CablelineEdit_8.setPlaceholderText(_translate("Form", "Cable_SN_8", None))
        self.CablelineEdit_3.setPlaceholderText(_translate("Form", "Cable_SN_3", None))
        self.label.setText(_translate("Form", "Slot #1", None))
        self.label_17.setText(_translate("Form", "Slot #2", None))
        self.label_18.setText(_translate("Form", "Slot #3", None))
        self.label_19.setText(_translate("Form", "Slot #4", None))
        self.label_20.setText(_translate("Form", "Slot #5", None))
        self.label_21.setText(_translate("Form", "Slot #6", None))
        self.label_22.setText(_translate("Form", "Slot #7", None))
        self.label_23.setText(_translate("Form", "Slot #8", None))
        self.label_24.setText(_translate("Form", "Slot #9", None))
        self.label_25.setText(_translate("Form", "Slot #10", None))
        self.label_26.setText(_translate("Form", "Slot #11", None))
        self.label_27.setText(_translate("Form", "Slot #12", None))
        self.label_28.setText(_translate("Form", "Slot #13", None))
        self.label_29.setText(_translate("Form", "Slot #14", None))
        self.label_30.setText(_translate("Form", "Slot #15", None))
        self.label_31.setText(_translate("Form", "Slot #16", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_cable), _translate("Form", "Cable SN", None))
        self.BatterylineEdit_10.setPlaceholderText(_translate("Form", "Battery_SN_10", None))
        self.BatterylineEdit_5.setPlaceholderText(_translate("Form", "Battery_SN_5", None))
        self.BatterylineEdit_9.setPlaceholderText(_translate("Form", "Battery_SN_9", None))
        self.BatterylineEdit_11.setPlaceholderText(_translate("Form", "Battery_SN_11", None))
        self.BatterylineEdit_14.setPlaceholderText(_translate("Form", "Battery_SN_14", None))
        self.BatterylineEdit_6.setPlaceholderText(_translate("Form", "Battery_SN_6", None))
        self.BatterylineEdit_15.setPlaceholderText(_translate("Form", "Battery_SN_15", None))
        self.BatterylineEdit_1.setPlaceholderText(_translate("Form", "Battery_SN_1", None))
        self.BatterylineEdit_12.setPlaceholderText(_translate("Form", "Battery_SN_12", None))
        self.BatterylineEdit_4.setPlaceholderText(_translate("Form", "Battery_SN_4", None))
        self.BatterylineEdit_7.setPlaceholderText(_translate("Form", "Battery_SN_7", None))
        self.BatterylineEdit_13.setPlaceholderText(_translate("Form", "Battery_SN_13", None))
        self.BatterylineEdit_16.setPlaceholderText(_translate("Form", "Battery_SN_16", None))
        self.BatterylineEdit_2.setPlaceholderText(_translate("Form", "Battery_SN_2", None))
        self.BatterylineEdit_8.setPlaceholderText(_translate("Form", "Battery_SN_8", None))
        self.BatterylineEdit_3.setPlaceholderText(_translate("Form", "Battery_SN_3", None))
        self.label_32.setText(_translate("Form", "Slot #13", None))
        self.label_33.setText(_translate("Form", "Slot #3", None))
        self.label_34.setText(_translate("Form", "Slot #9", None))
        self.label_35.setText(_translate("Form", "Slot #11", None))
        self.label_36.setText(_translate("Form", "Slot #15", None))
        self.label_37.setText(_translate("Form", "Slot #7", None))
        self.label_38.setText(_translate("Form", "Slot #10", None))
        self.label_39.setText(_translate("Form", "Slot #6", None))
        self.label_40.setText(_translate("Form", "Slot #1", None))
        self.label_41.setText(_translate("Form", "Slot #4", None))
        self.label_42.setText(_translate("Form", "Slot #2", None))
        self.label_43.setText(_translate("Form", "Slot #5", None))
        self.label_44.setText(_translate("Form", "Slot #8", None))
        self.label_45.setText(_translate("Form", "Slot #12", None))
        self.label_46.setText(_translate("Form", "Slot #14", None))
        self.label_47.setText(_translate("Form", "Slot #16", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_hybridcell), _translate("Form", "Battery SN", None))
        self.groupBox_5.setTitle(_translate("Form", "item picture", None))
        self.groupBox_6.setTitle(_translate("Form", "info", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.info), _translate("Form", "test", None))
        self.radioButton.setText(_translate("Form", "vin", None))
        self.radioButton_2.setText(_translate("Form", "vcap", None))
        self.radioButton_3.setText(_translate("Form", "temp", None))
        self.groupBox_7.setTitle(_translate("Form", "dut #1", None))
        self.groupBox_8.setTitle(_translate("Form", "dut #2", None))
        self.groupBox_9.setTitle(_translate("Form", "dut #3", None))
        self.groupBox_10.setTitle(_translate("Form", "dut #4", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.charts), _translate("Form", "charts", None))
        self.label_PN.setText(_translate("Form", "Part Number: ", None))
        self.label_REV.setText(_translate("Form", "Revision: ", None))
        self.label_DES.setText(_translate("Form", "Description: ", None))
        self.submit_pushButton.setText(_translate("Form", "submit", None))
        self.checkBox.setText(_translate("Form", "EditMode", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.configuration), _translate("Form", "configuration", None))
        self.search_lineEdit.setPlaceholderText(_translate("Form", "search by serial number", None))
        self.search_pushButton.setText(_translate("Form", "Search", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Form", "test log", None))
        self.title_label.setText(_translate("Form", "AGIGA UPGEM UFT V5.3.3", None))
        self.start_pushButton.setText(_translate("Form", "START", None))
        self.Mode4in1.setText(_translate("Form", "4 in 1", None))
        self.groupBox4.setTitle(_translate("Form", "Slot #4", None))
        self.sn_lineEdit_4.setPlaceholderText(_translate("Form", "Serial Number", None))
        self.groupBox10.setTitle(_translate("Form", "Slot #10", None))
        self.sn_lineEdit_10.setPlaceholderText(_translate("Form", "Serial Number", None))
        self.groupBox1.setTitle(_translate("Form", "Slot #1", None))
        self.sn_lineEdit_1.setPlaceholderText(_translate("Form", "Serial Number", None))
        self.groupBox2.setTitle(_translate("Form", "Slot #2", None))
        self.sn_lineEdit_2.setPlaceholderText(_translate("Form", "Serial Number", None))
        self.groupBox3.setTitle(_translate("Form", "Slot #3", None))
        self.sn_lineEdit_3.setPlaceholderText(_translate("Form", "Serial Number", None))
        self.groupBox5.setTitle(_translate("Form", "Slot #5", None))
        self.sn_lineEdit_5.setPlaceholderText(_translate("Form", "Serial Number", None))
        self.groupBox6.setTitle(_translate("Form", "Slot #6", None))
        self.sn_lineEdit_6.setPlaceholderText(_translate("Form", "Serial Number", None))
        self.groupBox7.setTitle(_translate("Form", "Slot #7", None))
        self.sn_lineEdit_7.setPlaceholderText(_translate("Form", "Serial Number", None))
        self.groupBox8.setTitle(_translate("Form", "Slot #8", None))
        self.sn_lineEdit_8.setPlaceholderText(_translate("Form", "Serial Number", None))
        self.groupBox9.setTitle(_translate("Form", "Slot #9", None))
        self.sn_lineEdit_9.setPlaceholderText(_translate("Form", "Serial Number", None))
        self.groupBox11.setTitle(_translate("Form", "Slot #11", None))
        self.sn_lineEdit_11.setPlaceholderText(_translate("Form", "Serial Number", None))
        self.groupBox12.setTitle(_translate("Form", "Slot #12", None))
        self.sn_lineEdit_12.setPlaceholderText(_translate("Form", "Serial Number", None))
        self.groupBox13.setTitle(_translate("Form", "Slot #13", None))
        self.sn_lineEdit_13.setPlaceholderText(_translate("Form", "Serial Number", None))
        self.groupBox14.setTitle(_translate("Form", "Slot #14", None))
        self.sn_lineEdit_14.setPlaceholderText(_translate("Form", "Serial Number", None))
        self.groupBox15.setTitle(_translate("Form", "Slot #15", None))
        self.sn_lineEdit_15.setPlaceholderText(_translate("Form", "Serial Number", None))
        self.groupBox16.setTitle(_translate("Form", "Slot #16", None))
        self.sn_lineEdit_16.setPlaceholderText(_translate("Form", "Serial Number", None))

from matplotlibwidget import MatplotlibWidget
